In [0]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

Using TensorFlow backend.


In [0]:
#fix random seed reproductivity
seed = 7
np.random.seed(seed)

In [0]:
import io
from google.colab import files
uploaded = files.upload()
df = pd.read_csv(io.StringIO(uploaded['sonar.all-data'].decode('utf-8')))
df

Saving sonar.all-data to sonar.all-data


0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032  R
0    0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044  R
1    0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078  R
2    0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117  R
3    0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094  R
4    0.0286  0.0453  0.0277  0.0174  0.0384  ...  0.0057  0.0027  0.0051  0.0062  R
5    0.0317  0.0956  0.1321  0.1408  0.1674  ...  0.0092  0.0143  0.0036  0.0103  R
6    0.0519  0.0548  0.0842  0.0319  0.1158  ...  0.0085  0.0047  0.0048  0.0053  R
7    0.0223  0.0375  0.0484  0.0475  0.0647  ...  0.0065  0.0093  0.0059  0.0022  R
8    0.0164  0.0173  0.0347  0.0070  0.0187  ...  0.0032  0.0035  0.0056  0.0040  R
9    0.0039  0.0063  0.0152  0.0336  0.0310  ...  0.0042  0.0003  0.0053  0.0036  R
10   0.0123  0.0309  0.0169  0.0313  0.0358  ...  0.0026  0.0092  0.0009  0.0044  R
11   0.0079  0.0086  0.0055  0.0250  0.0344  ...  0.0059  0.0058  0.0059  0.0032  R
12   0.0090  0.0062  0.0253  0.0489  0.1197  ...  0.0158  0.0053  0.0189  0.0102  R
13   0.0124  0.0433  0.0604  0.0449  0.0597  ...  0.0114  0.0196  0.0147  0.0062  R
14   0.0298  0.0615  0.0650  0.0921  0.1615  ...  0.0152  0.0049  0.0200  0.0073  R
15   0.0352  0.0116  0.0191  0.0469  0.0737  ...  0.0095  0.0015  0.0073  0.0067  R
16   0.0192  0.0607  0.0378  0.0774  0.1388  ...  0.0045  0.0037  0.0112  0.0075  R
17   0.0270  0.0092  0.0145  0.0278  0.0412  ...  0.0120  0.0132  0.0070  0.0088  R
18   0.0126  0.0149  0.0641  0.1732  0.2565  ...  0.0181  0.0094  0.0116  0.0063  R
19   0.0473  0.0509  0.0819  0.1252  0.1783  ...  0.0049  0.0082  0.0028  0.0027  R
20   0.0664  0.0575  0.0842  0.0372  0.0458  ...  0.0024  0.0162  0.0109  0.0079  R
21   0.0099  0.0484  0.0299  0.0297  0.0652  ...  0.0029  0.0160  0.0106  0.0134  R
22   0.0115  0.0150  0.0136  0.0076  0.0211  ...  0.0029  0.0037  0.0070  0.0041  R
23   0.0293  0.0644  0.0390  0.0173  0.0476  ...  0.0105  0.0160  0.0095  0.0011  R
24   0.0201  0.0026  0.0138  0.0062  0.0133  ...  0.0007  0.0024  0.0057  0.0044  R
25   0.0151  0.0320  0.0599  0.1050  0.1163  ...  0.0011  0.0019  0.0023  0.0062  R
26   0.0177  0.0300  0.0288  0.0394  0.0630  ...  0.0099  0.0057  0.0032  0.0019  R
27   0.0100  0.0275  0.0190  0.0371  0.0416  ...  0.0117  0.0020  0.0091  0.0058  R
28   0.0189  0.0308  0.0197  0.0622  0.0080  ...  0.0099  0.0092  0.0052  0.0075  R
29   0.0240  0.0218  0.0324  0.0569  0.0330  ...  0.0054  0.0019  0.0066  0.0023  R
..      ...     ...     ...     ...     ...  ...     ...     ...     ...     ... ..
177  0.0197  0.0394  0.0384  0.0076  0.0251  ...  0.0041  0.0045  0.0047  0.0054  M
178  0.0394  0.0420  0.0446  0.0551  0.0597  ...  0.0101  0.0068  0.0053  0.0087  M
179  0.0310  0.0221  0.0433  0.0191  0.0964  ...  0.0015  0.0056  0.0067  0.0054  M
180  0.0423  0.0321  0.0709  0.0108  0.1070  ...  0.0056  0.0021  0.0043  0.0017  M
181  0.0095  0.0308  0.0539  0.0411  0.0613  ...  0.0042  0.0030  0.0031  0.0033  M
182  0.0096  0.0404  0.0682  0.0688  0.0887  ...  0.0109  0.0036  0.0043  0.0018  M
183  0.0269  0.0383  0.0505  0.0707  0.1313  ...  0.0043  0.0027  0.0055  0.0057  M
184  0.0340  0.0625  0.0381  0.0257  0.0441  ...  0.0057  0.0051  0.0033  0.0058  M
185  0.0209  0.0191  0.0411  0.0321  0.0698  ...  0.0062  0.0087  0.0070  0.0042  M
186  0.0368  0.0279  0.0103  0.0566  0.0759  ...  0.0009  0.0086  0.0110  0.0052  M
187  0.0089  0.0274  0.0248  0.0237  0.0224  ...  0.0021  0.0069  0.0060  0.0018  M
188  0.0158  0.0239  0.0150  0.0494  0.0988  ...  0.0034  0.0046  0.0022  0.0021  M
189  0.0156  0.0210  0.0282  0.0596  0.0462  ...  0.0056  0.0056  0.0048  0.0024  M
190  0.0315  0.0252  0.0167  0.0479  0.0902  ...  0.0054  0.0035  0.0001  0.0055  M
191  0.0056  0.0267  0.0221  0.0561  0.0936  ...  0.0037  0.0024  0.0034  0.0007  M
192  0.0203  0.0121  0.0380  0.0128  0.0537  ...  0.0028 

In [0]:
df.head()

0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032  R
0  0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044  R
1  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078  R
2  0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117  R
3  0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094  R
4  0.0286  0.0453  0.0277  0.0174  0.0384  ...  0.0057  0.0027  0.0051  0.0062  R

[5 rows x 61 columns]

In [0]:
dataset = df.values
print(dataset[0])
print(dataset.ndim)
print(dataset.shape)
print(type(dataset))

[0.0453 0.0523 0.0843 0.0689 0.1183 0.2583 0.2156 0.3481 0.3337 0.2872
 0.4918 0.6552 0.6919 0.7797 0.7464 0.9444 1.0 0.8874 0.8024 0.7818 0.5212
 0.4052 0.3957 0.3914 0.325 0.32 0.3271 0.2767 0.4423 0.2028 0.3788 0.2947
 0.1984 0.2341 0.1306 0.4182 0.3835 0.1057 0.184 0.197 0.1674 0.0583
 0.1401 0.1628 0.0621 0.0203 0.053 0.0742 0.0409 0.0061 0.0125 0.0084
 0.0089 0.0048 0.0094 0.0191 0.014 0.0049 0.0052 0.0044 'R']
2
(207, 61)
<class 'numpy.ndarray'>


In [0]:
x = dataset[:, 0:60].astype(float)
y= dataset[:,60]
print(x[0])
print(y)
print(x.shape)
print(y.shape)

[0.0453 0.0523 0.0843 0.0689 0.1183 0.2583 0.2156 0.3481 0.3337 0.2872
 0.4918 0.6552 0.6919 0.7797 0.7464 0.9444 1.     0.8874 0.8024 0.7818
 0.5212 0.4052 0.3957 0.3914 0.325  0.32   0.3271 0.2767 0.4423 0.2028
 0.3788 0.2947 0.1984 0.2341 0.1306 0.4182 0.3835 0.1057 0.184  0.197
 0.1674 0.0583 0.1401 0.1628 0.0621 0.0203 0.053  0.0742 0.0409 0.0061
 0.0125 0.0084 0.0089 0.0048 0.0094 0.0191 0.014  0.0049 0.0052 0.0044]
['R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M

In [0]:
LE = LabelEncoder()
LE.fit(y)
y_encode = LE.transform(y)
y_encode

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
#To create a baseline
from keras import optimizers
def create_baseline():
  network = Sequential()
  network.add(Dense(60, activation = 'relu' , input_shape = (60,)))
  network.add(Dense(1, activation ='sigmoid'))
  network.compile(optimizer = 'rmsprop' , loss = 'binary_crossentropy' , metrics=['accuracy'])
  return network

In [0]:
#evaluate
estimator = KerasClassifier(build_fn = create_baseline , epochs = 100 , batch_size = 5 , verbose =0)
kfold = StratifiedKFold(n_splits = 10 , shuffle = True , random_state = seed)
results = cross_val_score(estimator , x , y_encode , cv= kfold)
print("Results : %2f%%(%2f%%)" %(results.mean()*100, results.std()*100))


W0827 07:50:52.221846 140303861704576 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0827 07:50:52.240642 140303861704576 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0827 07:50:52.247563 140303861704576 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0827 07:50:52.277106 140303861704576 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0827 07:50:52.297330 140303861704576 deprecation_wrappe

Results : 79.705629%(6.046413%)


In [0]:
#Evaluate Baseline model
np.random.seed(seed)
estimators =[]
estimators.append(('standarize' , StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn = create_baseline , epochs=100 , batch_size =5 , verbose = 0)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(n_splits = 10, shuffle= True , random_state= seed)
results = cross_val_score(pipeline , x , y_encode , cv= kfold)
print("Standarized : %2f%%(%.2f%%)" %(results.mean()*100 , results.std()*100))

Standarized : 83.062771%(6.58%)


In [0]:
#TO EVALUATE THE SMALLER NETWORK

def create_smaller():
  small_network = Sequential()
  small_network.add(Dense(30, activation= 'relu',input_shape=(60,)))
  small_network.add(Dense(1, activation = 'sigmoid'))
  small_network.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy' , metrics =['acc'])
  return small_network

In [0]:
#Run
estimators =[]
estimators.append(('standarize' , StandardScaler()))
estimators.append(('mlp' , KerasClassifier(build_fn = create_smaller , epochs =100 , batch_size = 5 , verbose=0)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(n_splits =10 , shuffle = True , random_state = seed)
results = cross_val_score(pipeline , x , y_encode , cv= kfold)
print('smaller: %2f%%(%2f%%)' % (results.mean()*100 , results.std()*100))


smaller: 83.112555%(5.700074%)


In [0]:
#TO CREATE A larger network
from keras import optimizers 
def create_larger():
  large_network = Sequential()
  large_network.add(Dense(60, activation = 'relu' , input_shape =(60,)))
  large_network.add(Dense(30, activation='relu'))
  large_network.add(Dense(1, activation='sigmoid'))
  large_network.compile(optimizer = 'rmsprop' , loss = 'binary_crossentropy' , metrics=['acc'])
  return large_network

In [0]:
#RUn 
estimators = []
estimators.append(('standarize' , StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn = create_larger , epochs = 100 , batch_size = 5 , verbose =0 )))
pipeline = Pipeline(estimators)
kfold= StratifiedKFold(n_splits = 10 , shuffle = True , random_state= seed)
results = cross_val_score(pipeline , x , y_encode , cv= kfold)
print("larger : %2f%% (%2f%%)" % (results.mean()*100 , results.std()*100))

larger : 81.564936% (6.211201%)


In [0]:
#Create baseline 
from keras import optimizers 
from keras import regularizers
def create_final():
  final_network = Sequential()
  final_network.add(Dense(30, activation= 'relu' , input_shape=(60,)))
  final_network.add(Dense(1, activation='sigmoid'))
  final_network.compile(optimizer = 'rmsprop' , loss= 'binary_crossentropy' , metrics=['acc'])
  return final_network

In [0]:
#Evaluate Model

estimator = KerasClassifier(build_fn = create_final , epochs=100, batch_size = 5 , verbose=0)
kfold= StratifiedKFold(n_splits= 10 , shuffle=True , random_state=seed)
results = cross_val_score(estimator , x , y_encode , cv = kfold)
print("Results : %2f%%(%2f%%)" %(results.mean()*100 , results.std()*100))


Results : 80.729438%(6.359174%)


In [0]:
#Functional API
from keras.layers import Input , Dense
from keras.models import Model
def functional_model():
  inputs = Input(shape=(60,))
  z = Dense(30, activation='relu')(inputs)
  outputs= Dense(1, activation='sigmoid')(z)
  model= Model(inputs, outputs)
  model.compile(optimizer = 'Adam', loss='binary_crossentropy' , metrics=['acc'])
  return model

In [0]:
#Run the model
estimators=[]
estimators.append(('standarize' , StandardScaler()))
estimators.append(('mlp' , KerasClassifier(build_fn= functional_model , epochs = 100 , batch_size=5 , verbose=0)))
pipeline = Pipeline(estimators)
kfold= StratifiedKFold(n_splits= 10 , shuffle=True , random_state= seed)
results= cross_val_score(pipeline, x , y_encode , cv= kfold)
print('funcational api: %2f%%(%2f%%)'%(results.mean()*100 , results.std()*100))

funcational api: 84.015152%(6.891404%)


In [0]:
#Build Model with Model subclassing 
import tensorflow as tf
class SubclassModel(tf.keras.Model):
  def __init__(self):
    super(SubclassModel, self).__init__()
    self.dense1= tf.keras.layers.Dense(60, activation= tf.nn.relu)
    self.dense2= tf.keras.layers.Dense(30, activation= tf.nn.relu)
    self.dense3= tf.keras.layers.Dense(1, activation= tf.nn.sigmoid)
  def call(self,inputs):
    x = self.dense1(inputs)
    x= self.dense2(x)
    return self.dense3(x)
def finalModel():
  model = SubclassModel()
  model.compile(loss= 'binary_crossentropy' , optimizer = 'adam' , metrics= ['acc'])
  return model
    
    

In [0]:
estimators =[]
estimators.append(('standarize' , StandardScaler()))
estimators.append(('mlp' , KerasClassifier(build_fn= finalModel , epochs = 100 , batch_size= 5 , verbose=0)))
pipeline= Pipeline(estimators)
kfold= StratifiedKFold(n_splits = 10 , shuffle= True , random_state= seed)
results = cross_val_score(pipeline , x , y_encode, cv=kfold) 
print('Subclass larger Model : %2f%%(%2f%%)'% (results.mean()*100, results.std()*100))


W0827 08:22:07.439453 140303861704576 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Subclass larger Model : 83.541126%(6.258041%)


In [0]:
#without scikit learn

print(x)
print(y_encode)


[[0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 [0.01   0.0171 0.0623 ... 0.0044 0.004  0.0117]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [0]:
complete_data = dataset.copy()
np.random.shuffle(complete_data)
data = complete_data[:,0:60].astype('float32')
labels= complete_data[:,60]
le = LabelEncoder()
le.fit(labels)
labels_encode= le.transform(labels).astype('float32')
print(labels_encode)
print(data.dtype)
train_data= data[:140]
test_data=data[140:]
train_labels= labels_encode[:140]
test_labels= labels_encode[140:]
print(train_data.shape)
print(test_data.shape)
print(train_labels.shape)
print(test_labels.shape)
print(train_labels[0])


[1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0.
 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.
 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0.
 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0.
 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1.
 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0.
 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0.
 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1.]
float32
(140, 60)
(67, 60)
(140,)
(67,)
1.0


In [0]:
def build_model():
  model= Sequential()
  model.add(Dense(60, activation='relu' , input_shape=(60,)))
  model.add(Dense(30, activation='relu'))
  model.add(Dense(1 , activation='sigmoid'))
  model.compile(optimizer='Adam' , loss= 'binary_crossentropy' , metrics=['acc'])
  return model

In [0]:
k=4
num_val_samples= len(train_data)//k
num_epochs= 100

for i in range(k):
  print('processing fold#' , i)
  val_data = train_data[i* num_val_samples: (i+1) * num_val_samples]
  val_labels = train_labels[i* num_val_samples : (i+1) * num_val_samples]
  partial_train_data= np.concatenate([train_data[:i* num_val_samples], train_data[(i+1)*num_val_samples:]], axis=0)
  partial_train_labels = np.concatenate([train_labels[:i*num_val_samples], train_labels[(i+1)*num_val_samples:]], axis=0)
  
  model= build_model()
  model.fit(partial_train_data, partial_train_labels , epochs= num_epochs , batch_size=5 , verbose= 0)
  loss , acc = model.evaluate(val_data , val_labels, verbose=0)
  print(acc)

processing fold# 0
0.8857142865657807
processing fold# 1
0.7714285722800663
processing fold# 2
0.7714285714285715
processing fold# 3
0.6285714302744184


In [0]:
def last_model():
  model = Sequential()
  model.add(Dense(60 , activation='relu' , input_shape=(60,)))
  model.add(Dense(30, activation='relu'))
  model.add(Dense(1 , activation='sigmoid'))
  model.compile(optimizer='Adam' , loss='binary_crossentropy' , metrics=['acc'])
  return model

model= last_model()
model.fit(train_data , train_labels , epochs= 100 , batch_size= 5 , verbose=0)

In [0]:
history= model.evaluate(test_data , test_labels) 
history

67/67 [==============================] - 2s 23ms/step


[0.44837546901805186, 0.8656716417910447]